// nuxt-site/pages/[slug].vue
<template>
  <section v-if="page">
    <h1>{{ page.title_en }}</h1>
    <h2>{{ page.title_zh }}</h2>
    <p>{{ page.summary_en }}</p>
    <p>{{ page.summary_zh }}</p>
  </section>
  <section v-else>
    <h1>Not Found</h1>
  </section>
</template>

<script setup lang="ts">
const route = useRoute();
const { getPage } = useContent();
const page = getPage(String(route.params.slug || ""));
</script>

// nextjs-site/app/[slug]/page.tsx
import { notFound } from "next/navigation";
import { getPageBySlug, pages } from "../../lib/content";

export function generateStaticParams() {
  return pages
    .filter((p) => p.slug !== "")
    .map((p) => ({
      slug: p.slug
    }));
}

export default function DynamicPage({ params }: { params: { slug: string } }) {
  const page = getPageBySlug(params.slug);
  if (!page) return notFound();

  return (
    <section>
      <h1>{page.title_en}</h1>
      <h2>{page.title_zh}</h2>
      <p>{page.summary_en}</p>
      <p>{page.summary_zh}</p>
    </section>
  );
}
